targets:
  $default:
    builders:
      hive_generator:
        generate_for:
          - lib/features/vendor_inventory/data/models/*.dart
          - lib/features/cart/domain/models/*.dart
          - lib/features/wishlist/domain/models/*.dart
